### ISSUE TITLE
unable to load XOutput1_1.dll

### ISSUE THREAD

**Issue by 0project** [MTCKC/ProconXInput#9]
Unable to connect to ScpvBus
please help
edit: first issue resolved, but now it is unable to load XOutput1_1.dll

**Comment by MTCKC** [comment]
You'll need the XOutput1_1.dll from the release package in the same folder as ProconXInput.exe. Make sure you use the one from the 64-bit package if you're using the 64-bit ProconXInput, and likewise for the 32-bit version.
